config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

      root 'lists#index'
 get '/user', to: 'users#index', as: :user

get '/user/:id/tasks', to: 'users#show'
post '/user/:id/tasks', to: 'users#show', as: :show
get '/tasks/:id', to: 'tasks#show', as: :show_task
get '/tasks', to: 'tasks#index'
post '/lists/:id/tasks/new', to: 'tasks#create'
get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
patch 'tasks/:id', to: 'tasks#update'
delete 'tasks.:id', to: 'tasks#destroy'
delete 'lists/:id', to: 'lists#destroy'


  resources :lists, only: [:index, :show, :new, :create, :edit] do
    resources :tasks,  only: [:show, :index, :new, :edit]
end
resources :tasks, only: [:index, :show, :new, :create, :edit, :update]

 devise_for :users
end
Rails.application.configure do
  config.google_sign_in.client_id     = ENV['google_sign_in_client_id']
  config.google_sign_in.client_secret = ENV['google_sign_in_client_secret']
end
Rails.application.routes.draw do
  # ...
  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true




end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :users, through: :tasks

  validates_presence_of :name, uniqueness: true

  accepts_nested_attributes_for :tasks

  
end
 

app/models/task.rb
class Task < ActiveRecord::Base
  
belongs_to :list
belongs_to :user 

validates_presence_of :task, :details, :user_id, presence: true

 
scope :most_recent, -> {order(created_at: :desc).limit(2)}

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
       validates :email, presence: true
    validates :email, :email, uniqueness: true    


  has_many :tasks
  has_many :lists, through: :tasks

end

app/models/user_list.rb
class UserList < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
      before_action :authenticate_user!
    
      helper_method :current_user, :logged_in?
      
     def current_user
          @current_user ||= User.find_by(id: session[:user_id])
     end

     def logged_in?
          !!session{:user_id}
     end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  #before_action :require_login
  skip_before_action :verify_authenticity_token

  def index
    @user = User.find_by(@current_user)
    @lists = List.all
    @list = Task.most_recent
  end

  def show
   @list = List.find_by(id: params[:id])
   @task = Task.find_by(id: params[:list_id])
   @user= User.find_by(params[:id])
  end

 def new
   @user = User.find_by(@current_user)
    @list = List.new
    @list.tasks.build
    # @list.save
   end


  def create
    @list = List.new(list_params)
    if @list.id == @current_user
     
     @list.save
      redirect_to @list
    else
      flash[:notice] = "User ID must be your own"
      render :new
    end
  end

def edit
        @list = List.find_by(id: params[:id])
      
    end

    def update
        @list = List.find(params[:id])
        @list.update(list_params)
        redirect_to list_path(@list)
    end

  def destroy
  List.find(params[:id]).destroy
    redirect_to lists_path
  end


  private

  def list_params
    params.require(:list).permit(:name, :task, tasks_attributes: [:task, :completed, :due_date, :details, :user_id, :list_id])
  end

  def require_login
    return head(:forbidden) unless session.include? :user_id    
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token
#  before_action :task_params, only: [ :edit, :update, :index, :show]


  def index
    @tasks = Task.all
    @user = User.find_by(params[:id])
  end

def show
  @list = List.find_by(id: params[:list_id])
 @task = @list.tasks.find_by(id: params[:id])
 @user = User.find_by(params[:id])
end

 def new
  @list = List.find_by(id: params[:list_id])
   @task = Task.new
    @list = List.find_by(id: params[:list_id])
 end
 

 def create
   @task = Task.create(task_params)
  if   @task.save
   redirect_to tasks_path
    flash[:notice] = "New task saved."
  else
    flash[:notice] = "Not saved"
    render :new
  end
end
  
  def edit
    @task = Task.find(params[:id])
  end

def update 
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to list_tasks_path(@task)
end

  def destroy

    @task =  Task.find_by(id: params[:id]).destroy
   redirect_to list_tasks_path(@task)
  end


  private
  

  def task_params
     params.require(:task).permit(:task, :completed, :due_date, :details, :user_id, :list_id)
  end
end
 

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController
#  def index
#  @user = User.all
#  end

#  def show
  
#   @user = User.find_by(id: params[:id])
#  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
    # @user = User.find_by(@current_user)
    # @user_lists = User.by_name
    @user = User.all
    end
    
    def new
        @user = User.new
    end

    def create
   @user = User.find_by(username: params[:username])
   if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id]) 
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task Manager</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>  
</head>

<body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</p></br>
<div class="outline">
<%# <ul> <h1 class= "title"> Task Manager </h1></ul> %>

<%= yield %>
</div>
</body>
</html>

app/views/lists/_errors.html.erb
<% if @list.errors.any? %>
    <div>
    <h2>
        <%= pluralize(@list.errors.count, "error") %>
        prohibited this from being saved:
    </h2>

    <ul>
        <% @list.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/lists/_list.html.erb
<%= render 'errors' %>

<%= form_for(@list) do |list_form| %>
   <ul> <h4>List Name: <%= list_form.text_field :name, placeholder: "Create a List" %></h4>
     <%= list_form.fields_for :tasks, @list.tasks do |task_field| %>
        <h4> Task: <%= task_field.text_field :task, placeholder: "Create a Task" %></h4>
        <h4> Details: <%= task_field.text_field :details, placeholder: "Details" %></h4> 
        <h4> Belongs to: <%= task_field.text_field :user_id, placeholder: 'Confirm user ID'%> 
      <% end %>

      <h4><%= list_form.submit %></h4>
    <% end %>
  </ul>
</ul>

app/views/lists/edit.html.erb
<h2>Editing:</h2>
<h3><%= @list.name %></h3>
 <%= render 'list' %>

app/views/lists/index.html.erb
 <div class="title"> <h2>Welcome <%= @user.email %></h2> </div>

<h4><%= link_to "View tasks by user", user_path %> 
<h4><%= link_to "View all tasks", tasks_path %></h4> 

<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: ['action-button', 'log-out-button'] %>

<div class="tasks-container">

<div class=out>
<h2> Recently added </h2>
<ul>
<div class=quick>

 <% @list.each do |l| %>
 <div class= "list-item">
    <h4> <%= l.task %> </h4>
         </div>
      <% end %> 
      
       </div>
      </ul>

<div class="innerquick">
<h3> Quick view </h3>
      </div>
</div>
 

<div class="tasks-list">

  <h3 class='title'> Currently To Do:</h3>
  <h3><%= link_to "Add New", new_list_path  %></h3>
  
      <% @lists.each do |list| %>
      <h4 class="list-item"> <%= link_to list.name, list %> </h4>
      <% end %>
    </div>
  </div>
    </div> 
   
  </div>

app/views/lists/new.html.erb
<h4><%= link_to "view all lists", lists_path %></h4>
<ul><h2>Create New</h2>

<%= render 'list' %>

app/views/lists/show.html.erb
<h4><%= link_to "view all lists", lists_path %></h4>
<h4> <%= link_to "add new task",  new_list_task_url(@list) %> </h4>  

<ul> 

<h3> <%= @list.name %>   </h3>
<div class="list-item"> 
    
    
      <% @list.tasks.each do |l| %>
      <% if l.task.nil? %>
      <h4>Nothing to complete</h4>
      <% else %>
           <h4> 
           <input class="toggle-all" type="checkbox"> <%= link_to l.task, list_task_path(@list, l)%> 
            </h4> 
    <% end %> 
        <%end%>

    </div>
     <h5> this list belongs to: 
     <%= @user.email%> </h5>
     
</ul>

<%= button_to "Delete list", list_path(@list), :method => :delete %>

</div>
</ul>
 

app/views/tasks/_errors.html.erb
<% if @task.errors.any? %>
    <div>
    <h2>
        <%= pluralize(@task.errors.count, "error") %>
        prohibited this from being saved:
    </h2>

    <ul>
        <% @task.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

app/views/tasks/_form.html.erb
<%= render 'errors' %>
<div class="tasks-container">
<div class= " tasks-item" id=form >

<%= form_for :task do |f| %>
<%= f.hidden_field :list_id, value: @list.id %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

<%= f.label :task %>
<%= f.text_field :task %><br>
<%= f.label :details %>
<%= f.text_field :details %><br>
<%= f.label :user_id %>
<%= f.text_field :user_id %><br>
<%= f.submit %>
<% end %>
</div>
  <%# <%= params.inspect %>

</div>

app/views/tasks/_task.html.erb
<label>
<h4>  <%= @task.task %> </h4>
</label>

app/views/tasks/edit.html.erb
 <h4> <%= link_to 'View all lists', lists_path %> </h4>

<div class="tasks-container">
<div class= " tasks-item" id=form >


<%= form_for([@list, @task]) do |t| %>
<%= t.hidden_field :id, value: @task.id %>
<%= t.hidden_field :user_id %>
  <%= t.label 'task' %><br>
  <%= t.text_field :task %><br>

  <%= t.label 'details' %><br>
  <%= t.text_area :details%><br>

  <%= t.submit "update" %>
<% end %>


</div>

 

app/views/tasks/index.html.erb
<!-- when a user clicks to view tasks, it links to 'tasks/index' to view all tasks with their associated lists -->
<h4><%= link_to "view all lists", lists_path %></h4>
 <h1> All Tasks: </h1>

<div>
  <div>
    <ul class="tasks-list">
      <% @tasks.each do |t| %>
          <li class="list-item">
          <h3><%=t.task %></h3>
            <div>
             <h4><%= t.details %></h4>
             
            </div>
            <h5>belongs to <%=t.user.email%> </h5>
          </li>
          <%end%>
    </ul>
     
  </div>
  </div>
 
</div>

app/views/tasks/new.html.erb
<!-- when a user clicks to create a new task, routes to 'tasks/new' -->
<h4> <%= link_to 'View all lists', lists_path %> </h4>
 <h2> <%= 'New task for' %> </h2>
<h3> <%= @list.name %> </h3>
<%=render "form" %>

app/views/tasks/show.html.erb
<h4><%= link_to "view all lists", lists_path %></h4>
<h4><%= link_to "edit", edit_task_path %></h4> 
 <h3  class="tasks-header"> <%= @task.task %></h3>
 <div class="tasks-item"> 
 <div>
<h4>Details:</h4>
<p><%= @task.details %></p> 

</div>

</div>
 <h5>this task belongs to: 
     <%=@task.user.email %> </h5>
<%= button_to "Delete", tasks_path(@task), :method => :delete %>

app/views/users/index.html.erb
<div>
<h1> All Users: </h1>
  <div>
    <ul class="tasks-list">
      <% @user.each do |t| %>
          <li class="list-item">
          <h3><%= link_to t.email, show_path(t)%></h3> 
          </li>
          <%end%>
    </ul>
     
  </div>
  </div>
 
</div>

app/views/users/show.html.erb
<%= link_to "view all lists", lists_path %></h4>
 <h2> All tasks for </h2>
 <h1><%= @user.email%>: </h1>

<div>
  <div>
    <ul class="tasks-list">
    <div class="list-item">
    <% if !@user.tasks.nil? %>
      <% @user.tasks.each do |t| %>
          <h3><%=t.task %></h3>
          <h4><%= t.details %></h4>
          <%end%>
       <%else%>
            <h3> This user has no tasks to complete</h3>
         <%end%>
       </div> 
    </ul>
  </div>
  </div>
 